-- Bảng văn bản / kế hoạch theo dõi nghị quyết
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  doc_number text,
  issuer text,
  issue_date text,
  deadline text default 'Theo kế hoạch',
  level text default 'Trung ương' check (level in ('Trung ương', 'Thành ủy', 'Phường')),
  status text default 'Chưa thực hiện' check (status in ('Chưa thực hiện', 'Đang thực hiện', 'Hoàn thành')),
  assignee text default 'Văn phòng Đảng ủy',
  file_url text,
  doc_url text,
  file_name text,
  is_concretized boolean default false,
  concretized_by text,
  target_name text,
  target_percent numeric default 0,
  sub_targets text,
  created_at timestamptz default now()
);

create index if not exists tasks_level_idx on public.tasks(level);
create index if not exists tasks_status_idx on public.tasks(status);

-- Bảng tài khoản người dùng (đăng nhập nghiệp vụ)
create table if not exists public.app_users (
  id text primary key,
  username text not null unique,
  password text not null,
  full_name text not null,
  role text not null check (role in ('viewer', 'editor', 'admin')),
  created_at timestamptz default now()
);

-- Ứng dụng truy cập Supabase từ client với anon key, nên bật RLS và mở quyền public
alter table public.tasks enable row level security;
alter table public.app_users enable row level security;

create policy "Public access for tasks"
on public.tasks
for all
using (true)
with check (true);

create policy "Public access for app_users"
on public.app_users
for all
using (true)
with check (true);