-- Public task data is intentionally readable by the public dashboard.
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  doc_number text,
  issuer text,
  issue_date date,
  deadline date default '2026-12-31',
  level text default 'Trung ương' check (level in ('Trung ương', 'Thành ủy', 'Phường')),
  status text default 'Chưa thực hiện' check (status in ('Chưa thực hiện', 'Đang thực hiện', 'Hoàn thành')),
  assignee text default 'Văn phòng Đảng ủy',
  file_url text,
  doc_url text,
  file_name text,
  is_concretized boolean default false,
  concretized_by text,
  target_name text,
  target_percent numeric default 0,
  sub_targets jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create index if not exists tasks_level_idx on public.tasks(level);
create index if not exists tasks_status_idx on public.tasks(status);

-- Keep this column as text for compatibility with existing legacy accounts.
-- Supabase users are linked by storing auth.users.id as text in this column.
create table if not exists public.app_users (
  id text primary key,
  username text not null unique,
  auth_email text unique,
  full_name text not null,
  role text not null check (role in ('viewer', 'editor', 'admin')),
  created_at timestamptz default now()
);

alter table public.app_users add column if not exists auth_email text;
alter table public.app_users drop column if exists password;
create unique index if not exists app_users_auth_email_idx
  on public.app_users (lower(auth_email))
  where auth_email is not null;

-- Link the existing application username to the Supabase Auth user created
-- for username-only sign-in. The password remains managed by Supabase Auth.
update public.app_users
set auth_email = 'thainhatquang@gmail.com'
where lower(username) in ('admin', 'thainhatquang@gmail.com')
   or lower(auth_email) = 'thainhatquang@gmail.com';

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.app_users
  where id = auth.uid()::text
     or lower(auth_email) = lower(auth.jwt() ->> 'email')
  limit 1
$$;

create or replace function public.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_app_role() = 'admin', false)
$$;

create or replace function public.is_app_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_app_role() in ('editor', 'admin'), false)
$$;

revoke all on function public.current_app_role() from public;
revoke all on function public.is_app_admin() from public;
revoke all on function public.is_app_editor() from public;
grant execute on function public.current_app_role() to authenticated;
grant execute on function public.is_app_admin() to authenticated;
grant execute on function public.is_app_editor() to authenticated;

alter table public.tasks enable row level security;
alter table public.app_users enable row level security;

drop policy if exists "Tasks viewing" on public.tasks;
drop policy if exists "Tasks updating" on public.tasks;
drop policy if exists "Tasks management" on public.tasks;
drop policy if exists "Tasks public read" on public.tasks;
drop policy if exists "Tasks editor insert" on public.tasks;
drop policy if exists "Tasks editor update" on public.tasks;
drop policy if exists "Tasks admin delete" on public.tasks;

create policy "Tasks public read" on public.tasks
  for select using (true);
create policy "Tasks editor insert" on public.tasks
  for insert to authenticated
  with check (public.is_app_editor());
create policy "Tasks editor update" on public.tasks
  for update to authenticated
  using (public.is_app_editor())
  with check (public.is_app_editor());
create policy "Tasks admin delete" on public.tasks
  for delete to authenticated
  using (public.is_app_admin());

drop policy if exists "Users viewing" on public.app_users;
drop policy if exists "Users management" on public.app_users;
drop policy if exists "Users self or admin read" on public.app_users;
drop policy if exists "Users admin insert" on public.app_users;
drop policy if exists "Users admin update" on public.app_users;
drop policy if exists "Users admin delete" on public.app_users;

create policy "Users self or admin read" on public.app_users
  for select to authenticated
  using (
    id = auth.uid()::text
    or lower(auth_email) = lower(auth.jwt() ->> 'email')
    or public.is_app_admin()
  );
create policy "Users admin insert" on public.app_users
  for insert to authenticated
  with check (public.is_app_admin());
create policy "Users admin update" on public.app_users
  for update to authenticated
  using (public.is_app_admin())
  with check (public.is_app_admin());
create policy "Users admin delete" on public.app_users
  for delete to authenticated
  using (public.is_app_admin());

grant select on public.tasks to anon, authenticated;
grant insert, update, delete on public.tasks to authenticated;
grant select on public.app_users to authenticated;
grant insert, update, delete on public.app_users to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Resolve a username to its Supabase Auth email without exposing app_users
-- or passwords to the browser. The API uses this function before sign-in.
create or replace function public.resolve_login_email(login_username text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    nullif(app.auth_email, ''),
    linked_user.email,
    metadata_user.email
  )
  from public.app_users app
  left join auth.users linked_user on linked_user.id::text = app.id
  left join lateral (
    select au.email
    from auth.users au
    where lower(coalesce(
      au.raw_user_meta_data ->> 'username',
      au.raw_user_meta_data ->> 'user_name'
    )) = lower(app.username)
    order by au.created_at
    limit 1
  ) metadata_user on true
  where lower(app.username) = lower(login_username)
     or lower(app.auth_email) = lower(login_username)
  limit 1
$$;

revoke all on function public.resolve_login_email(text) from public;
grant execute on function public.resolve_login_email(text) to anon, authenticated;
