create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  assignee text default 'Chưa phân công',
  deadline text default 'Theo kế hoạch',
  priority text default 'Bình thường' check (priority in ('Bình thường', 'Khẩn cấp')),
  status text default 'Chưa thực hiện' check (status in ('Chưa thực hiện', 'Đang thực hiện', 'Hoàn thành')),
  level text default 'Trung ương' check (level in ('Trung ương', 'Thành ủy', 'Phường')),
  created_at timestamptz default now()
);

alter table public.tasks enable row level security;

create policy "Public access for tasks"
on public.tasks
for all
using (true)
with check (true);

create index if not exists tasks_level_idx on public.tasks(level);
create index if not exists tasks_status_idx on public.tasks(status);
